### ISSUE TITLE
 register gitlab-runner skipping

### ISSUE THREAD

**Issue by fabiocruzcoelho** [lean-delivery/ansible-role-gitlab-runner#15]
##### SUMMARY

Hello, I'm trying to use your role to register my gitlab-runner, but the task that registers is giving skip., Is there any obligatory variable besides the token and url for me to register?

##### ISSUE TYPE
 - Documentation Report

##### ANSIBLE VERSION

```
2.7.8
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  gather_facts: yes
  # connection: local
  tasks:
    - name: Register gitlab runner
      include_role:
        name: '../'
      vars:
       gitlab_runner_concurrent: 1
       gitlab_runner_skip_registration: true
```

##### ACTUAL RESULTS

```

```

**Comment by pavelpikta** [comment]
Hi @fcruzcoelho . Thanks for the report. It's will be fixed in the next minor release

**Comment by pavelpikta** [comment]
@fcruzcoelho hi, see this example 
```yaml
---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-gitlab-runner
      vars:
        gitlab_runner_concurrent: 4
        gitlab_runner_skip_registration: false
        gitlab_ci_token: runner-token
```
